import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,unlink} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
import ts from 'typescript';
import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {heightAt} from '../src/region-layout.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),cache=path.join(root,'node_modules/.cache');await mkdir(cache,{recursive:true});
const temporary=path.join(cache,`blackline-marine-${process.pid}.mjs`);
const source=(await readFile(path.join(root,'src/marine.ts'),'utf8')).replace("'./region-layout.mjs'",JSON.stringify(pathToFileURL(path.join(root,'src/region-layout.mjs')).href));
await writeFile(temporary,ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);
const {createMarine}=await import(pathToFileURL(temporary));await unlink(temporary);await RAPIER.init();
const tick=(boat,world,codes,frames=1)=>{for(let i=0;i<frames;i++){boat.step(1/60,{keys:new Set(codes),yaw:0,pitch:0});world.step();}};
test('launch boards from carrier stairs and refuses a moving disembarkation',()=>{const world=new RAPIER.World({x:0,y:-9.81,z:0}),boat=createMarine(new THREE.Scene(),world);world.step();assert.equal(boat.board(new THREE.Vector3(0,0,0)),false);assert.equal(boat.board(new THREE.Vector3(275,13.7,950)),true);tick(boat,world,['KeyW'],120);assert.ok(boat.snapshot().travelled>15);assert.equal(boat.tryExit(),null);tick(boat,world,[],180);const exit=boat.tryExit();assert.ok(exit instanceof THREE.Vector3);assert.ok(Math.abs(exit.y-(boat.snapshot().deckY+1.7))<.001);const ray=new RAPIER.Ray(exit,{x:0,y:-1,z:0});const hit=world.castRay(ray,3,true);assert.ok(hit,'the exit has a real deck collider beneath it');assert.equal(boat.piloting,false);world.free();});
test('launch stops at shoreline and cannot sail over land',()=>{const world=new RAPIER.World({x:0,y:-9.81,z:0}),boat=createMarine(new THREE.Scene(),world);world.step();boat.board(new THREE.Vector3(275,13.7,950));tick(boat,world,['KeyW','ShiftLeft'],2400);assert.ok(heightAt(boat.position.x,boat.position.z)<-1.6);assert.ok(boat.snapshot().collisionCount>0);assert.ok(boat.position.z>100,'shoreline blocks travel into the starting settlement');world.free();});
test('launch sweeps static obstacles and resets to its mooring',()=>{const world=new RAPIER.World({x:0,y:-9.81,z:0}),boat=createMarine(new THREE.Scene(),world);world.createCollider(RAPIER.ColliderDesc.cuboid(20,4,1).setTranslation(289,2,920));world.step();boat.board(new THREE.Vector3(275,13.7,950));tick(boat,world,['KeyW','ShiftLeft'],180);assert.ok(boat.position.z>927);assert.ok(boat.snapshot().collisionCount>0);boat.reset();assert.deepEqual(boat.position.toArray(),[289,.7,950]);assert.equal(boat.health,100);assert.equal(boat.piloting,false);world.free();});

test('coastal patrol moves, respects shot distance, and pays only one kill',()=>{const world=new RAPIER.World({x:0,y:-9.81,z:0}),boat=createMarine(new THREE.Scene(),world);world.step();const before=boat.snapshot().patrol.position;for(let i=0;i<120;i++){boat.stepPatrol(1/60,new THREE.Vector3(-500,4,1135),false,()=>{},()=>{});world.step();}assert.notDeepEqual(boat.snapshot().patrol.position,before);const target=new THREE.Vector3(...boat.snapshot().patrol.position).add(new THREE.Vector3(0,2,0)),origin=target.clone().add(new THREE.Vector3(0,0,40)),direction=new THREE.Vector3(0,0,-1);assert.equal(boat.hit(origin,direction,20),null);assert.equal(boat.hit(origin,direction,50,100).killed,false);assert.equal(boat.hit(origin,direction,50,100).killed,true);assert.equal(boat.hit(origin,direction,50,100),null);assert.equal(boat.snapshot().patrol.alive,false);boat.reset();assert.equal(boat.snapshot().patrol.alive,true);world.free();});

test('marine save restoration validates water and obstacles and preserves defeated patrol state',()=>{const world=new RAPIER.World({x:0,y:-9.81,z:0}),boat=createMarine(new THREE.Scene(),world);world.step();boat.setPatrolDefeated(true);assert.equal(boat.snapshot().patrol.alive,false);assert.equal(boat.restoreAt({x:289,y:.7,z:1010,yaw:1}),true);assert.equal(boat.snapshot().yaw,1);assert.equal(boat.piloting,false);assert.equal(boat.snapshot().patrol.alive,false);assert.equal(boat.restoreAt({x:0,y:.7,z:110}),false);assert.equal(boat.restoreAt({x:289,y:90,z:1010}),false);assert.equal(boat.restoreAt({x:289,y:.7,z:1010,yaw:NaN}),false);world.createCollider(RAPIER.ColliderDesc.cuboid(8,3,8).setTranslation(289,2,1050));world.step();assert.equal(boat.restoreAt({x:289,y:.7,z:1050}),false);assert.deepEqual(boat.position.toArray(),[289,.7,1010]);boat.setPatrolDefeated(false);assert.equal(boat.snapshot().patrol.health,150);world.free();});
