import {CONTRACTS,UPGRADES,contractProgress,upgradeCost} from './progression.mjs';
import './expedition-ui.css';
type Data={campaign:any;atBase:boolean;saveMessage:string};
export function createExpeditionUI(parent:HTMLElement,callbacks:{close:()=>void;accept:(id:string)=>void;buy:(id:string)=>void;track:(id:string)=>void;save:()=>void}){
 const root=document.createElement('section');root.id='expedition-panel';root.hidden=true;root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','Expedition journal');parent.append(root);let data:Data;
 function paint(){root.innerHTML=`<div class="expedition-shell"><header><div><small>ORISON / FIELD JOURNAL</small><h2>Your expedition</h2></div><button data-close aria-label="Close journal">RETURN TO FIELD ×</button></header><div class="expedition-status"><span>${Math.floor(data.campaign.salvage)} SALVAGE · ${data.campaign.discovered.length} DISCOVERIES · ${data.campaign.raids} RAIDS</span><span>${data.atBase?'REFIT AVAILABLE':'REFIT AT A FRIENDLY OR SECURED BASE'}</span></div><div class="expedition-columns"><section><h3>Choose your next story</h3><p>Optional contracts. Take any route, or leave the radio unanswered.</p><div id="contract-list"></div></section><section><h3>Equipment & Kestrel</h3><p>Spend recovered salvage on permanent expedition upgrades.</p><div id="upgrade-list"></div><h3>Field notes</h3><div id="journal-list"></div></section></div><footer><span>${data.saveMessage}</span><button data-save>SAVE EXPEDITION</button></footer></div>`;
 const contracts=root.querySelector('#contract-list')!;for(const c of CONTRACTS){const status=data.campaign.contracts?.[c.id],p=contractProgress(data.campaign,c),card=document.createElement('article');card.className='contract-card';const label=document.createElement('small');label.textContent=status==='complete'?'COMPLETED':status==='active'?`ACTIVE · ${Math.min(p.current,p.target)} / ${p.target}`:`${c.reward} SALVAGE`;const title=document.createElement('h4');title.textContent=c.title;const desc=document.createElement('p');desc.textContent=c.description;card.append(label,title,desc);const button=document.createElement('button');button.textContent=status==='complete'?'REWARD RECEIVED':status==='active'?(c.bearing?'SET BEARING ↗':'IN PROGRESS'):'ACCEPT CONTRACT';button.disabled=status==='complete'||(status==='active'&&!c.bearing);button.dataset.contract=c.id;button.onclick=()=>{if(!status)callbacks.accept(c.id);else if(c.bearing)callbacks.track(c.bearing);};card.append(button);contracts.append(card);}
 for(const u of UPGRADES){const level=data.campaign.upgrades?.[u.id]||0,cost=upgradeCost(data.campaign,u),card=document.createElement('article');card.className='upgrade-card';card.innerHTML=`<div><h4>${u.name} <small>${level}/${u.max}</small></h4><p>${u.description}${data.campaign.blueprints?.includes(u.id)?' Recovered blueprint: 25% refit discount.':''}</p></div>`;const button=document.createElement('button');button.dataset.upgrade=u.id;button.textContent=level>=u.max?'MAXIMUM':`${cost} SALVAGE`;button.disabled=level>=u.max||!data.atBase||data.campaign.salvage<cost;button.onclick=()=>callbacks.buy(u.id);card.append(button);root.querySelector('#upgrade-list')!.append(card);}
 const notes=data.campaign.journal||[];for(const note of notes.slice(0,8)){const el=document.createElement('p'),title=document.createElement('strong');title.textContent=note.title+' · ';el.append(title,document.createTextNode(note.text));root.querySelector('#journal-list')!.append(el);}if(!notes.length)root.querySelector('#journal-list')!.textContent='Your discoveries and recovered transmissions will appear here.';
 root.querySelector('[data-close]')!.addEventListener('click',callbacks.close);root.querySelector('[data-save]')!.addEventListener('click',callbacks.save);
 }
 root.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=Array.from(root.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')),i=items.indexOf(document.activeElement as HTMLButtonElement);e.preventDefault();items[(i+(e.shiftKey?-1:1)+items.length)%items.length]?.focus();});
 return{open(value:Data){data=value;root.hidden=false;paint();root.querySelector<HTMLButtonElement>('[data-close]')?.focus();},update(value:Data){data=value;if(!root.hidden)paint();},close(){root.hidden=true;},get visible(){return !root.hidden;}};
}
