import {CONTRACTS,UPGRADES,contractProgress,upgradeCost} from './progression.mjs';
import './expedition-ui.css';
export type ExpeditionData={campaign:any;atBase:boolean;saveMessage:string;planetName?:string;destinations?:{id:string;name:string;description:string;available:boolean;reason?:string}[];scanner?:{cooldown:number;range:number};war?:{label:string;description:string};boarding?:{label:string;description:string};missions?:any[];recovery?:{title:string;description:string}|null;controller?:boolean;mainQuest?:any;person?:any};
type Data=ExpeditionData;
export function createExpeditionUI(parent:HTMLElement,callbacks:{close:()=>void;accept:(id:string)=>void;buy:(id:string)=>void;track:(id:string)=>void;save:()=>void;scan?:()=>void;travel?:(id:string)=>void;mission?:(id:string)=>void;recovery?:()=>void;order?:(id:string)=>void;personQuest?:(id:string)=>void;mainTalk?:()=>void}){
 const root=document.createElement('section');root.id='expedition-panel';root.hidden=true;root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','Expedition journal');parent.append(root);let data:Data,section='missions',filter='all';
 function paint(){const focused=document.activeElement as HTMLElement,focusKey=root.contains(focused)?focused?.dataset.focus:undefined;const scroll=root.scrollTop;root.innerHTML=`<div class="expedition-shell"><header><div><small>ORISON / FIELD JOURNAL</small><h2>Missions & expedition</h2></div><button data-close aria-label="Close journal">${data.controller?'B · RETURN TO FIELD':'RETURN TO FIELD ×'}</button></header><div class="expedition-status"><span>${Math.floor(data.campaign.salvage)} SALVAGE · ${data.campaign.discovered.length} DISCOVERIES · ${data.campaign.raids} RAIDS</span><span>${data.atBase?'REFIT AVAILABLE':'REFIT AT A FRIENDLY OR SECURED BASE'}</span></div><nav class="expedition-tabs" aria-label="Journal sections"><button data-section="missions">MISSIONS</button><button data-section="equipment">EQUIPMENT & TRAVEL</button><button data-section="squad">SQUAD</button>${data.person?'<button data-section="people">CONVERSATION</button>':''}</nav>${data.controller?'<p class="expedition-controller-hint">A · Select &nbsp; B · Back &nbsp; LB / RB · Tabs &nbsp; D-pad / Left stick · Navigate</p>':''}<div class="expedition-columns"><section data-page="missions"><h3>A Signal Home</h3><p>Follow the main story, or take a detour to help the people you meet. Accepted side quests stay here with their map bearings.</p><div id="main-quest-card"></div><h3>Side quests</h3><p>Talk to residents in villages and towns to find work. Look for the gold conversation markers nearby.</p><label class="mission-filter">Show <select id="mission-filter" data-focus="filter"><option value="all">All accepted quests</option><option value="active">Active</option><option value="complete">Completed</option></select></label><div id="contract-list"></div></section><section data-page="equipment"><h3>Equipment & Kestrel</h3><p>Spend recovered salvage on permanent expedition upgrades.</p><div id="upgrade-list"></div><div id="expedition-systems"></div><h3>Field notes</h3><div id="journal-list"></div></section></div><section data-page="people" id="resident-conversation"></section><section data-page="squad"><h3>Your squad, your call</h3><p>Give an explicit order. Your companions keep a supporting role.</p><div class="squad-actions"><button data-order="KeyQ">FOCUS AIMED TARGET</button><button data-order="KeyB">HOLD / FOLLOW</button><button data-order="KeyJ">REQUEST AMMUNITION</button><button data-order="KeyK">REQUEST MEDIC</button></div></section><footer><span>${data.saveMessage}</span><button data-save>SAVE EXPEDITION</button></footer></div>`;
 const contracts=root.querySelector('#contract-list')!;
 if(data.mainQuest){const q=data.mainQuest,card=document.createElement('article');card.className='contract-card mission-featured';const label=document.createElement('small'),title=document.createElement('h4'),desc=document.createElement('p'),button=document.createElement('button');label.textContent=q.complete?'MAIN QUEST COMPLETE':`MAIN QUEST · CHAPTER ${q.chapter} / ${q.total}`;title.textContent=q.title;desc.textContent=q.description;button.textContent=q.complete?'FLEET SIGNAL RESTORED':'TRACK MAIN QUEST ↗';button.disabled=q.complete;button.dataset.mainQuest='';button.dataset.focus='main-quest';button.onclick=()=>callbacks.mission?.('main');card.append(label,title,desc,button);root.querySelector('#main-quest-card')!.append(card);}
 if(data.person){const person=data.person,view=root.querySelector('#resident-conversation')!,label=document.createElement('small'),title=document.createElement('h3'),line=document.createElement('p');label.textContent=person.role+' / '+person.town;title.textContent=person.name;line.className='resident-dialogue';line.textContent=person.dialogue;view.append(label,title,line);
 if(person.mainAction){const button=document.createElement('button');button.dataset.mainTalk='';button.textContent=person.mainAction;button.onclick=()=>callbacks.mainTalk?.();view.append(button);}
 for(const quest of person.quests){const card=document.createElement('article');card.className='contract-card';const h=document.createElement('h4'),p=document.createElement('p'),button=document.createElement('button');h.textContent=quest.title;p.textContent=quest.description+' · '+quest.reward+' salvage';button.dataset.personQuest=quest.id;button.textContent=quest.status==='complete'?'COMPLETED':quest.status==='active'?'TRACK ACCEPTED QUEST':'I CAN HELP · ACCEPT QUEST';button.disabled=quest.status==='complete';button.onclick=()=>callbacks.personQuest?.(quest.id);card.append(h,p,button);view.append(card);}
 const leave=document.createElement('button');leave.dataset.leaveConversation='';leave.textContent='BACK TO THE SETTLEMENT';leave.onclick=callbacks.close;view.append(leave);}
 for(const m of data.missions??[]){if(filter!=='all'&&m.status!==filter)continue;const card=document.createElement('article');card.className='contract-card'+(m.id==='raider'?' mission-featured':'');const label=document.createElement('small'),title=document.createElement('h4'),desc=document.createElement('p'),detail=document.createElement('p'),button=document.createElement('button');label.textContent=`${m.status.toUpperCase()} · ${m.giver} · ${m.location}`;title.textContent=m.title;desc.textContent=m.description;detail.textContent=`${m.current} / ${m.total} · ${m.reward} salvage · ${m.instruction}`;button.textContent=m.status==='complete'?'COMPLETED':m.status==='active'?'TRACK MISSION ↗':'START & TRACK ↗';button.disabled=m.status==='complete';button.dataset.contract=m.id;button.dataset.focus='mission:'+m.id;button.onclick=()=>callbacks.mission?.(m.id);card.append(label,title,desc,detail,button);contracts.append(card);}
 if(!contracts.children.length)contracts.textContent='No accepted side quests here yet. Lia and Tomas in Pathfinder Landing are a good place to meet people.';
 const select=root.querySelector<HTMLSelectElement>('#mission-filter')!;select.value=filter;select.onchange=()=>{filter=select.value;paint();};
 function showSection(){root.querySelectorAll<HTMLElement>('[data-page]').forEach(el=>el.hidden=el.dataset.page!==section);root.querySelectorAll<HTMLButtonElement>('[data-section]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.section===section)));}
 root.querySelectorAll<HTMLButtonElement>('[data-section]').forEach(button=>button.onclick=()=>{section=button.dataset.section!;showSection();});showSection();
 root.querySelectorAll<HTMLButtonElement>('[data-order]').forEach(button=>button.onclick=()=>callbacks.order?.(button.dataset.order!));
 for(const u of UPGRADES){const level=data.campaign.upgrades?.[u.id]||0,cost=upgradeCost(data.campaign,u),card=document.createElement('article');card.className='upgrade-card';card.innerHTML=`<div><h4>${u.name} <small>${level}/${u.max}</small></h4><p>${u.description}${data.campaign.blueprints?.includes(u.id)?' Recovered blueprint: 25% refit discount.':''}</p></div>`;const button=document.createElement('button');button.dataset.upgrade=u.id;button.textContent=level>=u.max?'MAXIMUM':`${cost} SALVAGE`;button.disabled=level>=u.max||!data.atBase||data.campaign.salvage<cost;button.onclick=()=>callbacks.buy(u.id);card.append(button);root.querySelector('#upgrade-list')!.append(card);}
 const notes=data.campaign.journal||[];for(const note of notes.slice(0,8)){const el=document.createElement('p'),title=document.createElement('strong');title.textContent=note.title+' · ';el.append(title,document.createTextNode(note.text));root.querySelector('#journal-list')!.append(el);}if(!notes.length)root.querySelector('#journal-list')!.textContent='Your discoveries and recovered transmissions will appear here.';
 const systems=root.querySelector('#expedition-systems')!;
 if(data.planetName)root.querySelector('header small')!.textContent=`${data.planetName} / FIELD JOURNAL`;
 function systemSection(title:string,description:string){const card=document.createElement('section'),h=document.createElement('h3'),p=document.createElement('p');card.className='expedition-system';h.textContent=title;p.textContent=description;card.append(h,p);systems.append(card);return card;}
 if(data.scanner){const ready=data.scanner.cooldown<=0,card=systemSection('Discovery scanner',`Reveal nearby resources, life and signals within ${Math.round(data.scanner.range)} m. ${ready?'Pulse ready.':`Recharging · ${Math.ceil(data.scanner.cooldown)} s remaining.`}`),button=document.createElement('button');button.dataset.scan='';button.textContent=ready?(data.controller?'A · SCAN SURROUNDINGS':'V · SCAN SURROUNDINGS'):'SCANNER RECHARGING';button.disabled=!ready||!callbacks.scan;button.onclick=()=>callbacks.scan?.();card.append(button);}
 if(data.destinations?.length){const card=systemSection('Star chart','Choose a world. Your expedition and discoveries travel with you.');for(const destination of data.destinations){const row=document.createElement('article'),title=document.createElement('h4'),desc=document.createElement('p'),button=document.createElement('button');row.className='travel-card';title.textContent=destination.name;desc.textContent=destination.description+(destination.reason?' '+destination.reason:'');button.dataset.travel=destination.id;button.textContent=destination.available?'SET JUMP · '+destination.name.toUpperCase():'JUMP UNAVAILABLE';button.disabled=!destination.available||!callbacks.travel;button.onclick=()=>callbacks.travel?.(destination.id);row.append(title,desc,button);card.append(row);}}
 if(data.war)systemSection(data.war.label,data.war.description);
 if(data.boarding)systemSection(data.boarding.label,data.boarding.description);
 root.querySelector('[data-close]')!.addEventListener('click',callbacks.close);root.querySelector('[data-save]')!.addEventListener('click',callbacks.save);
 root.querySelectorAll<HTMLElement>('button,input,select').forEach((el,i)=>{const action=['section','order','upgrade','travel','personQuest','mainTalk','leaveConversation','close','save','scan'].find(key=>key in el.dataset);el.dataset.focus??=action?action+':'+el.dataset[action]:'control:'+i;});if(focusKey){const enabled=Array.from(root.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled)')).filter(el=>!el.closest('[hidden]'));(enabled.find(el=>el.dataset.focus===focusKey)??enabled.find(el=>el.dataset.section===section)??enabled[0])?.focus({preventScroll:true});}root.scrollTop=scroll;
 }
 root.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=Array.from(root.querySelectorAll<HTMLButtonElement>('button:not(:disabled),select')).filter(e=>e.getClientRects().length>0),i=items.indexOf(document.activeElement as HTMLButtonElement);e.preventDefault();items[(i+(e.shiftKey?-1:1)+items.length)%items.length]?.focus();});
 return{open(value:Data,tab='missions'){data=value;section=tab;root.hidden=false;paint();root.scrollTop=0;(section==='people'?root.querySelector<HTMLButtonElement>('[data-main-talk]:not(:disabled),[data-person-quest]:not(:disabled),[data-leave-conversation]'):root.querySelector<HTMLButtonElement>('[data-section="'+section+'"]'))?.focus();},update(value:Data){data=value;if(!root.hidden)paint();},close(){root.hidden=true;},get visible(){return !root.hidden;}};
}
