import {heightAt,SEA_LEVEL,getWorldSites} from './region-layout.mjs';
import './field-map.css';
export type MapSnapshot={position:{x:number,y?:number,z:number},yaw:number,completed:string[],discovered:string[],tracked:string|null,patrols:{x:number,z:number,alive:boolean}[],intel:boolean,allies?:{x:number,z:number,alive:boolean}[],ship?:{x:number,z:number}};
export function createFieldMap(container:HTMLElement,callbacks:{onTrack:(id:string,site?:any)=>void,onClose:()=>void}){
 const overlay=document.createElement('section');overlay.className='field-map';overlay.dataset.testid='field-map';overlay.hidden=true;overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-labelledby','atlas-title');
 overlay.innerHTML=`<header class="fm-header"><div><p class="fm-eyebrow">ORISON / FRONTIER ATLAS</p><h2 id="atlas-title">A world to get lost in.</h2></div><button class="fm-close">Back to adventure <span>ESC</span></button></header><div class="fm-body"><div class="fm-map-column"><div class="fm-chart"><canvas aria-label="Planet terrain, ocean, settlements, ships and current position"></canvas><div class="atlas-zoom"><button data-zoom="in" aria-label="Zoom in">+</button><button data-zoom="out" aria-label="Zoom out">−</button><button data-center>Locate me</button></div><span class="atlas-scale"></span></div><div class="fm-legend"><span>◆ You</span><span style="color:#83d1c8">● Safe haven</span><span style="color:#eb936e">● Pirates</span><span style="color:#d7ba80">◇ Relics</span></div><p class="fm-map-note">Drag to explore · Wheel to zoom · Select a destination to set a bearing. Fly or walk there.</p></div><aside class="fm-missions"><p class="fm-eyebrow">PLACES, NOT A MISSION CHAIN</p><p class="fm-instruction">Raid a camp. Find a ruin. Land on a carrier. Head for the station above the clouds.</p><div class="fm-site-list"></div></aside></div><footer class="fm-footer"><span class="fm-coordinate"></span><span>TERRAIN CONTINUES BEYOND THIS VIEW</span></footer>`;
 container.append(overlay);const canvas=overlay.querySelector('canvas')!,ctx=canvas.getContext('2d')!,terrain=document.createElement('canvas'),tc=terrain.getContext('2d')!;terrain.width=terrain.height=220;let snapshot:MapSnapshot,span=4400,center={x:0,z:0},drag:{x:number,y:number,cx:number,cz:number}|null=null,sites:any[]=[],markers:{x:number,y:number,id:string}[]=[];
 const chart=overlay.querySelector('.fm-chart') as HTMLElement;
 function land(){const pixels=tc.createImageData(220,220);for(let row=0;row<220;row++)for(let col=0;col<220;col++){const x=center.x+(col/220-.5)*span,z=center.z+(row/220-.5)*span,h=heightAt(x,z),i=(row*220+col)*4,above=h>SEA_LEVEL,relief=Math.min(45,Math.max(0,h)*.18);pixels.data[i]=above?68+relief:15;pixels.data[i+1]=above?88+relief:43+Math.max(-20,h*.18);pixels.data[i+2]=above?69+relief*.7:60+Math.max(-20,h*.18);pixels.data[i+3]=255;}tc.putImageData(pixels,0,0);sites=getWorldSites(center.x,center.z,span*.8);render();cards();}
 function point(x:number,z:number){return{x:(x-center.x)/span*canvas.width+canvas.width/2,y:(z-center.z)/span*canvas.height+canvas.height/2};}
 function render(){if(!snapshot)return;canvas.width=Math.max(400,chart.clientWidth);canvas.height=Math.max(250,chart.clientHeight);ctx.drawImage(terrain,0,0,canvas.width,canvas.height);markers=[];const labels:{x:number,y:number,w:number,h:number}[]=[];const current=point(snapshot.position.x,snapshot.position.z),tracked=sites.find(s=>s.id===snapshot.tracked);
 if(tracked){const t=point(tracked.x,tracked.z);ctx.setLineDash([6,6]);ctx.strokeStyle='#efbd7c99';ctx.beginPath();ctx.moveTo(current.x,current.y);ctx.lineTo(t.x,t.y);ctx.stroke();ctx.setLineDash([]);}
 for(const s of sites){const p=point(s.x,s.z);if(p.x<12||p.x>canvas.width-12||p.y<15||p.y>canvas.height-15)continue;markers.push({...p,id:s.id});ctx.fillStyle=snapshot.completed.includes(s.id)?'#829d84':s.faction==='friendly'?'#83d1c8':s.faction==='pirate'?'#eb936e':'#d7ba80';ctx.beginPath();ctx.arc(p.x,p.y,s.id===snapshot.tracked?7:4,0,Math.PI*2);ctx.fill();ctx.font='11px Arial';ctx.textAlign='center';if(span<6000||s.kind==='station'||s.kind==='carrier'){const text=(s.kind==='station'?'↑ ORBIT / ':'')+s.name,w=ctx.measureText(text).width+10,x=Math.max(w/2+5,Math.min(canvas.width-w/2-5,p.x)),y=Math.max(17,p.y-12),r={x:x-w/2,y:y-12,w,h:17};if(!labels.some(a=>r.x<a.x+a.w&&r.x+r.w>a.x&&r.y<a.y+a.h&&r.y+r.h>a.y)){ctx.fillText(text,x,y);labels.push(r);}}}
 if(snapshot.ship){const p=point(snapshot.ship.x,snapshot.ship.z);ctx.strokeStyle='#c2e4fa';ctx.strokeRect(p.x-6,p.y-6,12,12);}for(const a of snapshot.allies??[]){const p=point(a.x,a.z);ctx.fillStyle='#8ccbd1';ctx.fillRect(p.x-2,p.y-2,4,4);}ctx.save();ctx.translate(current.x,current.y);ctx.rotate(-snapshot.yaw);ctx.fillStyle='#fff0c6';ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(6,7);ctx.lineTo(0,4);ctx.lineTo(-6,7);ctx.closePath();ctx.fill();ctx.restore();overlay.querySelector('.atlas-scale')!.textContent=`${(span/1000).toFixed(1)} km across`;overlay.querySelector('.fm-coordinate')!.textContent=`${Math.round(snapshot.position.x)} E / ${Math.round(snapshot.position.z)} N · ALT ${Math.round(snapshot.position.y??0)} m`;
 }
 function cards(){const ordered=[...sites].sort((a,b)=>Math.hypot(a.x-snapshot.position.x,a.z-snapshot.position.z)-Math.hypot(b.x-snapshot.position.x,b.z-snapshot.position.z));const list=overlay.querySelector('.fm-site-list')!;list.replaceChildren();for(const s of ordered.slice(0,18)){const b=document.createElement('button');b.className='fm-site'+(s.id===snapshot.tracked?' is-tracked':'');b.dataset.site=s.id;const d=Math.hypot(s.x-snapshot.position.x,s.z-snapshot.position.z,s.elevation-(snapshot.position.y??0));b.innerHTML=`<span class="fm-site-top">${s.kind.replaceAll('-',' ')} · ${snapshot.completed.includes(s.id)?'SECURED':s.faction.toUpperCase()}<span class="fm-site-distance">${d>1000?(d/1000).toFixed(1)+' km':Math.round(d)+' m'}</span></span><strong>${s.name}</strong><span class="fm-site-effect">${s.description}</span><span class="fm-track-label">SET BEARING ↗</span>`;b.onclick=()=>callbacks.onTrack(s.id,s);list.append(b);}}
 overlay.querySelector('.fm-close')!.addEventListener('click',callbacks.onClose);overlay.querySelector('[data-center]')!.addEventListener('click',()=>{center={x:snapshot.position.x,z:snapshot.position.z};land();});overlay.querySelectorAll<HTMLButtonElement>('[data-zoom]').forEach(b=>b.onclick=()=>{span=Math.max(500,Math.min(20000,span*(b.dataset.zoom==='in'?.6:1.6)));land();});canvas.addEventListener('wheel',e=>{e.preventDefault();span=Math.max(500,Math.min(20000,span*(e.deltaY>0?1.2:.8)));land();},{passive:false});canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,cx:center.x,cz:center.z};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointerup',e=>{if(!drag)return;const travel=Math.hypot(e.clientX-drag.x,e.clientY-drag.y);if(travel>5){center.x=drag.cx-(e.clientX-drag.x)/canvas.clientWidth*span;center.z=drag.cz-(e.clientY-drag.y)/canvas.clientHeight*span;}drag=null;if(travel<5){const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)*canvas.width/rect.width,y=(e.clientY-rect.top)*canvas.height/rect.height,marker=markers.find(m=>Math.hypot(m.x-x,m.y-y)<16);if(marker){callbacks.onTrack(marker.id,sites.find(s=>s.id===marker.id));return;}}land();});overlay.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=Array.from(overlay.querySelectorAll<HTMLButtonElement>('button')),i=items.indexOf(document.activeElement as HTMLButtonElement);e.preventDefault();items[(i+(e.shiftKey?-1:1)+items.length)%items.length]?.focus();});window.addEventListener('resize',()=>{if(!overlay.hidden)render();});return {open(value:MapSnapshot){snapshot=value;center={x:value.position.x,z:value.position.z};overlay.hidden=false;land();(overlay.querySelector('.fm-close') as HTMLButtonElement).focus();},update(value:MapSnapshot){snapshot=value;if(!overlay.hidden)render();},close(){overlay.hidden=true;}};
}
