import {targetNavigation,flightGuidance} from './navigation.mjs';
import './navigation-ui.css';
export type NavigationTarget={id:string;name:string;x:number;z:number;y?:number;elevation?:number;kind?:string;faction?:string};
export type NavigationSnapshot={position:{x:number;y:number;z:number};yaw:number;tracked?:NavigationTarget|null;ship?:NavigationTarget|null;aboard:boolean;flying?:boolean;speed?:number;altitude?:number;landed?:boolean;visible?:boolean;projected?:{x:number;y:number;behind?:boolean}};
export function createNavigationUI(parent:HTMLElement){
 const root=document.createElement('div');root.className='navigation-hud';root.dataset.testid='navigation-hud';root.innerHTML='<div class="nav-target" hidden><span class="nav-turn"></span><div><strong class="nav-name"></strong><small class="nav-distance"></small></div></div><div class="nav-ship" hidden></div><div class="nav-flight" hidden><strong></strong><span></span></div><div class="nav-world-pin" hidden><b>◇</b><span></span></div>';
 parent.append(root);parent.classList.add('has-navigation');const compass=parent.querySelector<HTMLElement>('#compass'),marker=document.createElement('i');marker.className='nav-compass-marker';marker.hidden=true;marker.textContent='◇';compass?.append(marker);const target=root.querySelector<HTMLElement>('.nav-target')!,turn=root.querySelector<HTMLElement>('.nav-turn')!,name=root.querySelector<HTMLElement>('.nav-name')!,distance=root.querySelector<HTMLElement>('.nav-distance')!,ship=root.querySelector<HTMLElement>('.nav-ship')!,flight=root.querySelector<HTMLElement>('.nav-flight')!,pin=root.querySelector<HTMLElement>('.nav-world-pin')!;
 return {update(value:NavigationSnapshot){
  root.hidden=value.visible===false;if(compass&&!marker.isConnected)compass.append(marker);const selected=value.aboard&&value.tracked?.id==='kestrel'?null:value.tracked,nav=targetNavigation(value.position,value.yaw,selected);target.hidden=!nav;marker.hidden=!nav;if(nav&&selected){const half=(compass?.clientWidth??180)/2-12;marker.style.transform=`translateX(${Math.max(-half,Math.min(half,nav.delta*2))}px)`;marker.textContent=nav.arrow;marker.title=selected.name;marker.dataset.target=selected.id;}
  if(nav&&selected){turn.textContent=nav.arrow;name.textContent=selected.name;distance.textContent=`${nav.distanceLabel} · ${nav.verticalLabel}${nav.offscreen?' · TURN '+(nav.delta<0?'LEFT':'RIGHT'):''}`;target.dataset.target=selected.id;target.classList.toggle('is-hostile',selected.faction==='pirate'||selected.faction==='hostile');const tick=parent.querySelector<HTMLElement>('#ship-tick');if(tick){tick.hidden=true;} }
  ship.hidden=value.aboard||!value.ship||selected?.id===value.ship.id;if(!ship.hidden&&value.ship){const n=targetNavigation(value.position,value.yaw,value.ship)!;ship.textContent=`${n.arrow} ${value.ship.name} · ${n.distanceLabel} · ${n.verticalLabel}`;}
  flight.hidden=!value.flying;if(value.flying){const guide=flightGuidance({position:value.position,tracked:selected??null,speed:value.speed??0,altitude:value.altitude??0,landed:value.landed??false});flight.querySelector('strong')!.textContent=guide.label;flight.querySelector('span')!.textContent=guide.detail;flight.classList.toggle('is-hostile',guide.danger);}
  pin.hidden=!nav||!selected||!value.projected;if(nav&&selected&&value.projected){const p=value.projected,offscreen=p.behind||p.x<.08||p.x>.92||p.y<.18||p.y>.72;pin.style.left=`${(p.behind?(nav.delta<0?.08:.92):Math.max(.08,Math.min(.92,p.x)))*100}%`;pin.style.top=`${(p.behind?.42:Math.max(.18,Math.min(.72,p.y)))*100}%`;pin.querySelector('b')!.textContent=offscreen?(nav.delta<0?'◀':'▶'):'◇';pin.querySelector('span')!.textContent=`${selected.name} · ${nav.distanceLabel} · ${nav.verticalLabel}`;pin.classList.toggle('at-left',p.behind?nav.delta<0:p.x<.2);pin.classList.toggle('at-right',p.behind?nav.delta>=0:p.x>.8);}
 },dispose(){root.remove();marker.remove();parent.classList.remove('has-navigation');}};
}
