export const MAIN_CONTRACTS=['coast','array','raider','orbit','echo-vault'];
export const QUEST_PEOPLE=[
 {id:'mara',name:'Mara Voss',role:'Pathfinder coordinator',town:'Pathfinder Landing',x:10,z:97,color:0x688f99,quests:[],greeting:'The crash cut our last link to the fleet. These settlements need a way to call home. I can help you put that link back together.'},
 {id:'lia',name:'Lia Sen',role:'Field cartographer',town:'Pathfinder Landing',x:-14,z:126,color:0xb48857,quests:['survey','surveyor'],greeting:'I used to draw coastlines. Now I mark places where people did not come back. Start with the fallen courier east of the crash, or follow the coast west toward the survey team. Bring me fresh observations and scanner readings.',followup:'Your journal can track our survey. Follow a road until something catches your eye, then scan the landmark. You do not need to take the same route twice.',thanks:'Those blank spaces on my map finally have names. The next convoy has a better chance because of you.'},
 {id:'tomas',name:'Tomas Reed',role:'Settlement medic',town:'Pathfinder Landing',x:17,z:78,color:0xb4bdb6,quests:['signals','rescue'],greeting:'We made room for everyone who came out of your wreck. Others are still calling: a survey team west of the crash, and prisoners aboard the Corsair. Pick a rescue when you are ready; I will keep the lamps on.',followup:'Check the distress marker in your journal. Clear the danger before approaching survivors. The Corsair crew need its engines disabled before you open their holding bay.',thanks:'Another voice checked in on the radio. Another family gets good news. That is what your work means here.'},
 {id:'iris',name:'Iris Okoye',role:'Harbour pilot',town:'Cold Harbour',x:11,z:8,color:0x648ba7,requires:'harbour',quests:['aces','breakwater'],greeting:'Thanks for opening the harbour. Pirate interceptors and the island battery are keeping our relief boats pinned down. I have work for a pilot willing to change that.',followup:'You can tackle the interceptors in Kestrel or go after Breakwater first. Give yourself room to brake on approach; that battery overlooks the carrier route.',thanks:'The relief route is open. I can finally tell the boat crews to start their engines.'},
 {id:'kito',name:'Kito Arlen',role:'Sunfall engineer',town:'Sunfall Expedition Port',x:42012,z:10,color:0xc59153,quests:['vesper-mine'],greeting:'The extraction crews built this town. Pirates took their mine and cut off our supplies. Clear the Obsidian camp and I can keep Sunfall running.',followup:'The Obsidian camp is marked in your journal. Clear its guards and recover the camp supplies. Every crate matters out here.',thanks:'We have supplies again. Tonight the workshop stays open, and tomorrow we start repairing the town.'},
 {id:'sela',name:'Sela Nadir',role:'Sunfall archivist',town:'Sunfall Expedition Port',x:41988,z:15,color:0x8c86a6,quests:['glass-basin'],greeting:'The observatory in the salt flats has been silent for generations. I think its archive survived. Would you recover it for us?',followup:'Follow the Glass Basin marker across the salt flats. Look for the archive terminal at the observatory; a scan alone will not retrieve its records.',thanks:'These records contain a sky no one here has ever seen. You brought a piece of this world back to us.'}
];
