import {stickVector} from './mobile-rules.mjs';
type Actions={key:(code:string,down:boolean)=>void;move:(x:number,z:number)=>void;look:(dx:number,dy:number)=>void;fire:(down:boolean)=>void;aim:(down:boolean)=>void;skip:()=>void;wake:()=>void};
export function createTouchControls(actions:Actions){
 const root=document.createElement('div');root.id='touch-controls';root.hidden=true;root.innerHTML=`<div id="touch-look" aria-label="Swipe to look"></div><nav class="touch-top" aria-label="Game tools"><button data-tap="Tab">MAP</button><button data-tap="KeyI">JOURNAL</button><button id="touch-more" aria-expanded="false">MORE</button><button data-tap="Escape" aria-label="Pause game">Ⅱ</button></nav><div id="touch-orders" hidden><button data-tap="KeyH">Find ship</button><button data-tap="KeyB">Squad hold / follow</button><button data-tap="KeyQ">Focus target</button><button data-tap="KeyJ">Request ammo</button><button data-tap="KeyG">Grenade</button><button data-tap="KeyM">Sound on / off</button></div><div id="touch-move" role="group" aria-label="Movement joystick"><span></span><small>MOVE</small></div><button id="touch-run" aria-pressed="false">RUN</button><div class="touch-actions"><button id="touch-aim" aria-pressed="false">AIM</button><button data-tap="KeyR" id="touch-reload">RELOAD</button><button id="touch-fire">FIRE</button><button data-hold="ControlLeft" id="touch-down">CROUCH</button><button data-hold="Space" id="touch-up">JUMP</button><button data-hold="KeyE" id="touch-use">USE</button></div><button data-tap="KeyF" id="touch-vehicle">BOARD</button><button id="touch-skip">SKIP ARRIVAL</button>`;
 document.getElementById('app')!.append(root);
 const el=(id:string)=>root.querySelector<HTMLElement>('#'+id)!;let enabled=false,aim=false,run=false,crouch=false,currentVehicle:'foot'|'ship'|'boat'='foot';
 const releases=new Map<number,()=>void>();let stickId:number|null=null,lookId:number|null=null,lastLook={x:0,y:0};
 const joystick=el('touch-move'),nub=joystick.querySelector('span')!;
 function release(id:number){const fn=releases.get(id);releases.delete(id);fn?.();}
 function capture(e:PointerEvent,target:HTMLElement,up:()=>void){e.preventDefault();e.stopPropagation();target.setPointerCapture(e.pointerId);releases.set(e.pointerId,up);actions.wake();}
 function reset(){for(const id of [...releases.keys()])release(id);stickId=lookId=null;actions.move(0,0);actions.fire(false);actions.aim(false);actions.key('ShiftLeft',false);actions.key('ControlLeft',false);aim=run=crouch=false;el('touch-down').setAttribute('aria-pressed','false');nub.style.transform='translate(0,0)';el('touch-aim').setAttribute('aria-pressed','false');el('touch-run').setAttribute('aria-pressed','false');el('touch-orders').hidden=true;el('touch-more').setAttribute('aria-expanded','false');}
 function moveStick(e:PointerEvent){const r=joystick.getBoundingClientRect(),v=stickVector(e.clientX-r.left-r.width/2,e.clientY-r.top-r.height/2,r.width*.42);actions.move(v.x,v.z);nub.style.transform=`translate(${v.x*r.width*.3}px,${v.z*r.height*.3}px)`;}
 joystick.addEventListener('pointerdown',e=>{if(stickId!==null)return;stickId=e.pointerId;capture(e,joystick,()=>{stickId=null;actions.move(0,0);nub.style.transform='translate(0,0)';});moveStick(e);});
 joystick.addEventListener('pointermove',e=>{if(e.pointerId===stickId)moveStick(e);});
 const look=el('touch-look');look.addEventListener('pointerdown',e=>{if(lookId!==null)return;lookId=e.pointerId;lastLook={x:e.clientX,y:e.clientY};capture(e,look,()=>{lookId=null;});});look.addEventListener('pointermove',e=>{if(e.pointerId!==lookId)return;actions.look(e.clientX-lastLook.x,e.clientY-lastLook.y);lastLook={x:e.clientX,y:e.clientY};});
 root.querySelectorAll<HTMLButtonElement>('[data-hold]').forEach(b=>{b.addEventListener('pointerdown',e=>{const code=b.dataset.hold!;if(code==='ControlLeft'&&currentVehicle==='foot'){capture(e,b,()=>{});crouch=!crouch;actions.key(code,crouch);b.setAttribute('aria-pressed',String(crouch));}else{capture(e,b,()=>actions.key(code,false));actions.key(code,true);}});});
 root.querySelectorAll<HTMLButtonElement>('[data-tap]').forEach(b=>b.addEventListener('click',()=>{actions.wake();actions.key(b.dataset.tap!,true);actions.key(b.dataset.tap!,false);el('touch-orders').hidden=true;el('touch-more').setAttribute('aria-expanded','false');}));
 let fireId:number|null=null,fireLast={x:0,y:0};el('touch-fire').addEventListener('pointerdown',e=>{if(fireId!==null)return;fireId=e.pointerId;fireLast={x:e.clientX,y:e.clientY};capture(e,el('touch-fire'),()=>{fireId=null;actions.fire(false);});if(run&&currentVehicle==='foot'){run=false;actions.key('ShiftLeft',false);el('touch-run').setAttribute('aria-pressed','false');}actions.fire(true);});el('touch-fire').addEventListener('pointermove',e=>{if(e.pointerId!==fireId)return;actions.look(e.clientX-fireLast.x,e.clientY-fireLast.y);fireLast={x:e.clientX,y:e.clientY};});
 el('touch-aim').onclick=()=>{aim=!aim;actions.aim(aim);el('touch-aim').setAttribute('aria-pressed',String(aim));};el('touch-run').onclick=()=>{run=!run;actions.key('ShiftLeft',run);el('touch-run').setAttribute('aria-pressed',String(run));};el('touch-more').onclick=()=>{const show=el('touch-orders').hidden;reset();el('touch-orders').hidden=!show;el('touch-more').setAttribute('aria-expanded',String(show));};el('touch-skip').onclick=()=>{actions.wake();actions.skip();};
 for(const name of ['pointerup','pointercancel','lostpointercapture'])root.addEventListener(name,e=>release((e as PointerEvent).pointerId));
 window.addEventListener('blur',reset);window.addEventListener('pagehide',reset);window.addEventListener('resize',reset);document.addEventListener('visibilitychange',()=>{if(document.hidden)reset();});
 return {reset,update(playing:boolean,intro:boolean,vehicle:'foot'|'ship'|'boat'){if(currentVehicle!==vehicle){reset();currentVehicle=vehicle;}if(enabled!==playing){enabled=playing;if(!playing)reset();root.hidden=!playing;}root.classList.toggle('touch-intro',intro);el('touch-up').textContent=vehicle==='ship'?'RISE':'JUMP';el('touch-down').textContent=vehicle==='ship'?'DESCEND':'CROUCH';el('touch-up').hidden=vehicle==='boat';el('touch-down').hidden=vehicle==='boat';el('touch-run').textContent=vehicle==='foot'?'RUN':'BOOST';el('touch-vehicle').textContent=vehicle==='foot'?'BOARD':'EXIT';}};
}
