import { chromium } from '@playwright/test';
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Users/jcrow/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1600,height:900},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://localhost:5180/');
await page.waitForFunction(()=>!!window.blacklineQA,{timeout:60000});
await page.waitForTimeout(2500);await page.screenshot({path:'qa/menu.png'});
await page.evaluate(()=>window.blacklineQA.start());await page.waitForTimeout(1000);
await page.screenshot({path:'qa/gameplay.png'});
await page.evaluate(()=>window.blacklineQA.look(.7,-.02));await page.waitForTimeout(500);await page.screenshot({path:'qa/port.png'});
await page.evaluate(()=>{window.blacklineQA.photo();document.getElementById('damage').style.opacity='0';});await page.waitForTimeout(300);await page.screenshot({path:'qa/arena.png'});
console.log(JSON.stringify({errors,snapshot:await page.evaluate(()=>window.blacklineQA.snapshot())}));
await browser.close();
