import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';import {heightAt,getWorldSites} from '../src/region-layout.mjs';
const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Users/jcrow/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe',args:['--enable-webgl','--ignore-gpu-blocklist']}),p=await b.newPage({viewport:{width:1440,height:900}}),errors=[],results=[];
p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const snap=()=>p.evaluate(()=>window.blacklineQA.snapshot());
async function check(name,run){await run();results.push({name,pass:true});console.log(name+': PASS');}
try{await p.goto('http://localhost:5180');await p.waitForFunction(()=>window.blacklineQA,null,{timeout:90000});await p.locator('#deploy').click();
await check('fresh player sees in-world arrival then escapes the crash',async()=>{assert((await snap()).opening.active);await p.waitForTimeout(1800);await p.screenshot({path:'qa/crashfall-arrival.png'});await p.waitForFunction(()=>!window.blacklineQA.snapshot().opening.active,null,{timeout:60000});const s=await snap();assert.equal(s.campaign.onboarding.stage,'cell');assert(Math.abs(s.position[2]-231)<2);assert.equal(s.climate.weather,'clear');await p.screenshot({path:'qa/crashfall-wreck.png'});});
await check('walk out of wreck and hold E to recover the physical power cell',async()=>{await p.keyboard.down('w');await p.waitForFunction(()=>window.blacklineQA.snapshot().position[2]<209,null,{timeout:15000});await p.keyboard.up('w');await p.keyboard.down('e');await p.waitForFunction(()=>window.blacklineQA.snapshot().campaign.onboarding.stage==='ship',null,{timeout:10000});await p.keyboard.up('e');assert.match(await p.locator('#waypoint-label').textContent(),/KESTREL/);});
await check('follow road on foot, install the cell, board and lift off',async()=>{await p.keyboard.down('w');await p.keyboard.down('Shift');await p.waitForFunction(()=>window.blacklineQA.snapshot().position[2]<115,null,{timeout:25000});await p.keyboard.up('w');await p.keyboard.up('Shift');await p.keyboard.down('d');await p.waitForFunction(()=>window.blacklineQA.snapshot().position[0]>7.5,null,{timeout:7000});await p.keyboard.up('d');await p.keyboard.down('e');await p.waitForFunction(()=>window.blacklineQA.snapshot().campaign.onboarding.stage==='launch',null,{timeout:10000});await p.keyboard.up('e');await p.screenshot({path:'qa/crashfall-ship.png'});await p.keyboard.press('f');assert((await snap()).flight.piloting);assert.equal((await snap()).campaign.onboarding.stage,'complete');assert.equal((await snap()).campaign.salvage,50);await p.keyboard.down('Space');await p.waitForTimeout(1800);await p.keyboard.up('Space');assert((await snap()).flight.altitude>5);});
await check('scrolling compass reads all four cardinal headings and ship shortcut works',async()=>{for(const [yaw,label]of [[0,'N · 000'],[-Math.PI/2,'E · 090'],[-Math.PI,'S · 180'],[Math.PI/2,'W · 270']]){await p.evaluate(y=>window.blacklineQA.look(y,0),yaw);await p.waitForTimeout(100);assert((await p.locator('#bearing').textContent()).startsWith(label));}await p.keyboard.press('h');assert.equal((await snap()).campaign.tracked,'kestrel');await p.keyboard.press('Tab');assert.equal(await p.locator('.fm-site').first().getAttribute('data-site'),'kestrel');await p.screenshot({path:'qa/crashfall-atlas.png'});await p.keyboard.press('Escape');});
await check('continue keeps recovered ship and never replays the opening',async()=>{assert(await p.evaluate(()=>window.blacklineQA.save()));await p.reload();await p.waitForFunction(()=>window.blacklineQA,null,{timeout:90000});await p.locator('#deploy').click();await p.waitForTimeout(300);const s=await snap();assert.equal(s.campaign.onboarding.stage,'complete');assert(!s.opening.active);assert.equal(s.campaign.salvage,50);});
for(const [name,x,z]of [['relay',-690,-505],['mining',780,-325],['roadside',177,50]]){await p.evaluate(({x,y,z})=>{const q=window.blacklineQA;q.start();q.setClimate({hour:11,weather:'clear'});q.teleport3(x,y,z);q.look(0,-.04);},{x,y:heightAt(x,z)+2,z});await p.waitForTimeout(250);await p.evaluate(()=>window.blacklineQA.photo());await p.screenshot({path:`qa/crashfall-${name}.png`});}
const variants=getWorldSites(0,0,3500).filter(s=>s.district==='market'||s.district==='salvage');for(const kind of ['market','salvage']){const s=variants.find(s=>s.district===kind);if(!s)continue;await p.evaluate(s=>{const q=window.blacklineQA;q.start();q.teleport3(s.x,s.elevation+3,s.z+40);q.look(0,0);},s);await p.waitForTimeout(200);await p.evaluate(()=>window.blacklineQA.photo());await p.screenshot({path:`qa/crashfall-${kind}.png`});}
assert.equal(errors.length,0,errors.join('\n'));}catch(e){results.push({pass:false,error:e.message,snapshot:await snap()});throw e;}finally{await writeFile('qa/crashfall-results.json',JSON.stringify({results,errors},null,2));await b.close();}
