import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',args:['--enable-webgl','--ignore-gpu-blocklist']}),p=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];
p.on('pageerror',e=>errors.push(e.message));p.on('crash',()=>errors.push('tab crashed'));
const snap=()=>p.evaluate(()=>window.blacklineQA.snapshot());async function check(name,fn){await fn();checks.push(name);console.log('PASS '+name);}async function board(){await p.evaluate(()=>{const q=window.blacklineQA,s=q.flight.position;q.teleport3(s.x+6,s.y-.45,s.z);});await p.waitForTimeout(250);await p.keyboard.press('f');await p.waitForFunction(()=>window.blacklineQA.snapshot().flight.piloting);}
try{await p.goto('http://localhost:5180');await p.waitForFunction(()=>window.blacklineQA,null,{timeout:90000});await p.selectOption('#quality','low',{force:true});await p.evaluate(()=>window.blacklineQA.start());
await check('Energy weapon swaps, fires independently of ammunition and recharges',async()=>{await p.keyboard.press('x');assert.equal((await snap()).weapon,'energy');await p.mouse.move(720,450);await p.mouse.down();await p.waitForTimeout(650);await p.mouse.up();const s=await snap();assert(s.energy<100&&s.ammo===30);await p.waitForTimeout(2300);assert((await snap()).energy>s.energy);await p.keyboard.press('x');assert.equal((await snap()).weapon,'ballistic');});
await check('Shield absorbs damage and requested medic heals health',async()=>{await p.evaluate(()=>window.blacklineQA.damage(20));assert((await snap()).shield<70);assert.equal((await snap()).health,100);await p.evaluate(()=>{window.blacklineQA.damage(120);window.blacklineQA.regroup();});const before=(await snap()).health;await p.keyboard.press('k');assert((await snap()).health>before);});
await check('Scanner discovers and rewards once, cooldown rejects repeated input',async()=>{await p.keyboard.press('v');const a=await snap();assert(a.campaign.scanned.length>0);assert(a.scanCooldown>0);await p.keyboard.press('v');assert.equal((await snap()).campaign.salvage,a.campaign.salvage);});
await check('Selected map destination appears on rotating compass',async()=>{await p.evaluate(()=>window.blacklineQA.track('station'));await p.waitForTimeout(150);const marker=p.locator('.nav-compass-marker');assert(await marker.isVisible());const before=await marker.getAttribute('style');await p.evaluate(()=>window.blacklineQA.look(-1.2,0));await p.waitForTimeout(150);assert.notEqual(await marker.getAttribute('style'),before);await p.keyboard.press('Tab');assert(await p.locator('.field-map').isVisible());await p.locator('button[data-target]').click();await p.screenshot({path:'qa/expansion-map.png'});await p.keyboard.press('Escape');});
await check('Journal travel reaches Vesper and save reload retains destination and ship',async()=>{await board();await p.evaluate(()=>{const q=window.blacklineQA,s=q.flight.position;q.flight.position.y=350;q.flight.velocity.set(0,0,0);q.teleport3(s.x,350,s.z);});await p.waitForTimeout(200);await p.keyboard.press('i');await p.locator('[data-section="equipment"]').click();assert(await p.locator('[data-travel="vesper"]').isEnabled());await p.locator('[data-travel="vesper"]').click();await p.waitForFunction(()=>window.blacklineQA.snapshot().planet==='vesper'&&window.blacklineQA.snapshot().mode==='playing',null,{timeout:30000});await p.waitForTimeout(300);assert((await snap()).flight.piloting);await p.screenshot({path:'qa/expansion-vesper.png'});await p.evaluate(()=>{window.blacklineQA.save();window.blacklineQA.load();});await p.waitForTimeout(500);const s=await snap();assert.equal(s.planet,'vesper');assert(s.flight.position[0]>40000);assert(s.position[0]>40000);assert(s.flight.landed);});
await check('Return travel and Corsair engines respond to real ship cannon hits',async()=>{await board();await p.evaluate(()=>{const q=window.blacklineQA,s=q.flight.position;q.flight.position.y=400;q.flight.velocity.set(0,0,0);q.teleport3(s.x,400,s.z);});await p.waitForTimeout(200);await p.keyboard.press('i');await p.locator('[data-section="equipment"]').click();await p.locator('[data-travel="orison"]').click();await p.waitForFunction(()=>window.blacklineQA.snapshot().planet==='orison'&&window.blacklineQA.snapshot().mode==='playing',null,{timeout:30000});await p.evaluate(()=>{const q=window.blacklineQA;q.flight.position.set(-564,23,1155);q.flight.velocity.set(0,0,0);q.teleport3(-564,23,1155);q.look(Math.PI/2,-.15);});await p.waitForTimeout(300);await p.mouse.down();await p.waitForTimeout(1300);await p.mouse.up();assert.equal((await snap()).boarding.stage,'rescue');});
await check('Boarding rescue and cargo objectives grant one-time rewards',async()=>{await p.evaluate(()=>{const q=window.blacklineQA;q.flight.position.set(-650,11.15,1164);q.flight.velocity.set(0,0,0);});await p.waitForTimeout(350);assert((await snap()).flight.landed);await p.keyboard.press('f');assert(!(await snap()).flight.piloting);await p.evaluate(()=>{const q=window.blacklineQA;q.teleport3(-650,10.7,1130);q.clear();});await p.waitForTimeout(200);await p.keyboard.down('e');await p.waitForTimeout(2400);await p.keyboard.up('e');assert((await snap()).campaign.rescued.includes('corsair'));assert.equal((await snap()).boarding.stage,'defend');await p.evaluate(()=>window.blacklineQA.clear());await p.waitForTimeout(200);assert.equal((await snap()).boarding.stage,'cargo');await p.evaluate(()=>window.blacklineQA.teleport3(-650,10.7,1140));await p.waitForTimeout(150);await p.keyboard.down('e');await p.waitForTimeout(2900);await p.keyboard.up('e');assert((await snap()).campaign.completed.includes('corsair'));const a=(await snap()).campaign.salvage;await p.keyboard.down('e');await p.waitForTimeout(2800);await p.keyboard.up('e');assert.equal((await snap()).campaign.salvage,a);await p.screenshot({path:'qa/expansion-corsair.png'});});
assert.deepEqual(errors,[]);
}finally{await writeFile('qa/expansion-results.json',JSON.stringify({checks,errors,snapshot:await snap().catch(()=>null)},null,2));await browser.close();}console.log(JSON.stringify({checks,errors}));
